/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.presentation.principal;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.awt.Rectangle;
import java.util.Observable;

/**
 *
 * Autores:
 *         Natalia Arce Rodriguez
 *         Michelle Delgado Meneses
 * 
 */

public class View extends javax.swing.JFrame implements java.util.Observer {

    //**************  MVC ***********
    Controller controller;
    Model model;
    
    public void setController(Controller controller){
        this.controller=controller;
    }

    public Controller getController() {
        return controller;
    }
    
    public void setModel(Model model){
        this.model=model;
         model.addObserver(this);
    }

    public Model getModel() {
        return model;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
//************** END MVC ***********
    
//**************  RESALTAR ***********
     ArrayList<Rectangle> coordenadas = new ArrayList<>();
     Rectangle guanacaste = new Rectangle(80,159,124,44); 
     Rectangle sanJose = new Rectangle(424,395,62,20); 
     Rectangle sanJose2 = new Rectangle(318,333,89,49); 
     Rectangle heredia = new Rectangle(400,145,50,94); 
     Rectangle cartago = new Rectangle(459,315,95,52); 
     Rectangle alajuela = new Rectangle(300,132,90,138);
     Rectangle alajuela2 = new Rectangle(188,91,168,35); 
     Rectangle limon = new Rectangle(588,329,72,106); 
     Rectangle limon2 = new Rectangle(475,192,77,13); 
     Rectangle puntarenas = new Rectangle(547,511,121,74); 
     Rectangle puntarenas2 = new Rectangle(555,456,58,39); 
     Rectangle puntarenas3 = new Rectangle(242,246,38,44);  
     Rectangle puntarenas4 = new Rectangle(173,314,33,42); 
     Rectangle normal2 = new Rectangle(593,4,251,263); 
     Rectangle normal3 = new Rectangle(10,404,428,324);

        public void agregar ()
    {
        coordenadas.add(guanacaste);
        coordenadas.add(sanJose);
        coordenadas.add(sanJose2);
        coordenadas.add(heredia);
        coordenadas.add(cartago);
        coordenadas.add(alajuela);
        coordenadas.add(alajuela2);
        coordenadas.add(limon);
        coordenadas.add(limon2);
        coordenadas.add(puntarenas); 
        coordenadas.add(puntarenas2);
        coordenadas.add(puntarenas3);
        coordenadas.add(puntarenas4);
        coordenadas.add(normal2); //10
        coordenadas.add(normal3);  //11
    }
//**************  END RESALTAR ***********
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        agregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Provincias = new javax.swing.JLabel();
        textFieldCedula = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JLabel();
        textFieldProvincia = new javax.swing.JLabel();
        textFieldCanton = new javax.swing.JLabel();
        textFieldDistrito = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        canton = new javax.swing.JComboBox<>();
        provincia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Provincias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/provincias.png"))); // NOI18N
        Provincias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProvinciasMouseMoved(evt);
            }
        });
        Provincias.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                ProvinciasComponentMoved(evt);
            }
        });

        textFieldCedula.setText("Cedula");

        textFieldNombre.setText("Nombre");

        textFieldProvincia.setText("Provincia");

        textFieldCanton.setText("Canton");

        textFieldDistrito.setText("Distrito");

        canton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Provincias, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCedula)
                            .addComponent(textFieldNombre))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldProvincia)
                            .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldCanton)
                                .addGap(136, 136, 136)
                                .addComponent(textFieldDistrito)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCedula)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldProvincia)
                    .addComponent(textFieldCanton)
                    .addComponent(textFieldDistrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Provincias, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        Provincias.getAccessibleContext().setAccessibleName("Provincias");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProvinciasComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProvinciasComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinciasComponentMoved

    private void ProvinciasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvinciasMouseMoved
        // TODO add your handling code here:
        double x = (double)evt.getX();
        double y = (double)evt.getY();
        for (int i=0;i<coordenadas.size();i++)
       {
           switch(i)
           {
               case 0:
                    if (coordenadas.get(i).contains(x,y))
                        {
                            ImageIcon guana = new ImageIcon("src/Imagenes/guanacaste.png");
                            Provincias.setIcon(guana);
                        }
                    break;
               case 1:
                   if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon sj = new ImageIcon("src/Imagenes/san jose.png");
                            Provincias.setIcon(sj);
                   }
                   break;
               case 2:
                       if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon sj2 = new ImageIcon("src/Imagenes/san jose.png");
                            Provincias.setIcon(sj2);
                   }
                   break;
               case 3:
                   if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon h = new ImageIcon("src/Imagenes/heredia.png");
                            Provincias.setIcon(h);
                   }
                   break;
               case 4:
                   if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon c = new ImageIcon("src/Imagenes/cartago.png");
                            Provincias.setIcon(c);
                   }
                   break;
               case 5:
                   if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon a = new ImageIcon("src/Imagenes/alajuela.png");
                            Provincias.setIcon(a);
                   }
                   break;
               case 6:
                    if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon a = new ImageIcon("src/Imagenes/alajuela.png");
                            Provincias.setIcon(a);
                   }
                   break;
               case 7:
                   if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon l = new ImageIcon("src/Imagenes/limon.png");
                            Provincias.setIcon(l);
                   }
                   break;
               case 8:
                    if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon l = new ImageIcon("src/Imagenes/limon.png");
                            Provincias.setIcon(l);
                   }
                    break;
               case 9:
                    if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon p = new ImageIcon("src/Imagenes/puntarenas.png");
                            Provincias.setIcon(p);
                   }
                    break;
               case 10:
                       if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon p = new ImageIcon("src/Imagenes/puntarenas.png");
                            Provincias.setIcon(p);
                   }
                       break;
               case 11:
                       if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon p = new ImageIcon("src/Imagenes/puntarenas.png");
                            Provincias.setIcon(p);
                   }
                       break;
               case 12:
                       if (coordenadas.get(i).contains(x, y))
                   {
                            ImageIcon p = new ImageIcon("src/Imagenes/puntarenas.png");
                            Provincias.setIcon(p);
                   }
                       break;
               case 13:
                        if (coordenadas.get(i).contains(x, y))
                        {
                            ImageIcon normal = new ImageIcon("src/Imagenes/provincias.png");
                            Provincias.setIcon(normal);
                        }
               case 14:
                        if (coordenadas.get(i).contains(x, y))
                         {
                            ImageIcon normal = new ImageIcon("src/Imagenes/provincias.png");
                            Provincias.setIcon(normal);
                        }
                        
           }

        }
    }//GEN-LAST:event_ProvinciasMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Provincias;
    private javax.swing.JComboBox<String> canton;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField provincia;
    private javax.swing.JLabel textFieldCanton;
    private javax.swing.JLabel textFieldCedula;
    private javax.swing.JLabel textFieldDistrito;
    private javax.swing.JLabel textFieldNombre;
    private javax.swing.JLabel textFieldProvincia;
    // End of variables declaration//GEN-END:variables


}
